### ISSUE TITLE
Source and Target documents are reversed

### ISSUE THREAD

**Issue by guillp** [json-patch-builder-online/json-patch-builder-online.github.io#1]
When generating a patch document between a Source document and a Target document, the page actually generates a reverse diff (that applied to the Target, gives the Source document).

`var diff = jsonpatch.compare(targetDocument, sourceDocument);`
should be
`var diff = jsonpatch.compare(sourceDocument, targetDocument);`

**Comment by gsferreira** [comment]
@guillp thanks for taking the time to report this!
Fixed.
